name: flickzone
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_story_list: ^1.0.4
  font_awesome_flutter: ^9.1.0
  outline_search_bar: ^2.2.0
  badges: ^2.0.1
  line_icons: ^2.0.1
  waterfall_flow: ^3.0.1
  get_it: ^7.1.3
  stacked: ^2.1.7
  cached_network_image: ^3.0.0
  firebase_core : ^1.2.0
  cloud_firestore: ^2.2.0
  simple_gesture_detector: ^0.2.0
  velocity_x: ^3.2.0
  flutter_launcher_icons: ^0.9.1
  splash_screen_view: ^3.0.0
  twilio_flutter: ^0.0.9
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  dio: ^4.0.0
  http: ^0.13.3
  path_provider:
  dart_date: ^1.1.0
  collapsible: ^1.0.0
  pull_to_refresh: ^2.0.0
  mvc_pattern: ^7.4.0
  device_info: ^2.0.2
  gradient_widgets: ^0.6.0
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.22.0
  percent_indicator: ^3.0.1
#  video_trimmer: ^0.5.4
  assets_audio_player: ^3.0.3+6
  image_picker: ^0.8.3+1
  rflutter_alert: ^2.0.4
  sliding_up_panel: ^2.0.0+1
  fab_circular_menu: ^1.0.2
  get: ^4.3.4
  flick_video_player: ^0.3.1
  flutter_video_newfeed: ^1.0.0+2
  avatar_glow: ^2.0.1
  getwidget: ^2.0.3
  tiktoklikescroller: ^0.1.6
  bottom_sheet: ^1.0.1
  visibility_detector: ^0.2.0
  flutter_downloader: ^1.6.1
  file_picker: ^4.0.0
  dropdown_plus: ^0.0.9
  video_compress: ^3.1.0
  widget_video_recorder: ^0.2.1
  expandable: ^5.0.1
  adv_image_picker: ^2.0.1+2
  cool_alert: ^1.1.0
  shimmer_animation: ^2.1.0+1
  liquid_progress_indicator: ^0.4.0
  flutter_image_slider: ^0.0.2
  likk_picker: ^1.0.7
  advance_image_picker: ^0.1.2
  u2flutter_player: ^0.0.6
  camera_roll_uploader: ^0.0.7
  location: ^4.3.0
  geocoder_flutter: ^0.2.3-prerelease
  permission_handler: ^8.1.6
  flutter_camera_view: ^0.0.1
  video_editor_sdk: ^2.0.0
  camera: ^0.9.4+1
  flutter_ffmpeg: ^0.4.2

dependency_overrides:
  android_path_provider: ^0.2.1
#  video_thumbnail: 0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: ^4.0.1
  dependency_validator: ^3.0.0


  flutter_lints: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
     - assets/icons/sample.mp4
     - assets/icons/vesdk_android_license.android
  fonts:
    - family:  TikTokIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf

 # SPLASHSCREEN CODE STARTS HERE
splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  color: "#ffffff"
  #background_image: "assets/splashscreen_image.png"

  # Optional parameters are listed below.
  image: assets/images/icon.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'